name: Windows

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
      - name: Install Swift
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-6.3.2-release
          swift-build: 6.3.2-RELEASE
      - name: Build
        shell: pwsh
        run: swift build
      - name: Test
        shell: pwsh
        run: swift test
